spring:
  application:
    name: yuni
  datasource:
    url: jdbc:h2:file:./data/yuni;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

yuni:
  base-url: https://coding.dashscope.aliyuncs.com/v1/chat
  # ok, i forgot this ~ now this key just a sample
  api-key: sk-sp-c3422acc21d24581bbd128027b36283d
  model: glm-5
  context-window: 202752
  max-tokens: 16384
  workspace: ~/YuniHome
  tavily-api-key: ${TAVILY_API_KEY:}
